### ISSUE TITLE
When I was running the demo,there was an error

### ISSUE THREAD

**Issue by yeyuanzheng177** [Duoluoluos/Emotion-Guided-Piano-Accompaniment-Generation#2]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 860/860 [00:00<00:00, 48075.46it/s]
Phrase Selection Begins:
         4 phrases in query lead sheet;
         Refer to [] as much as possible;
         Set note density filter: (0, 0) .
Searching for Phrase 1
Searching for Phrase 2
Searching for Phrase 3
Searching for Phrase 4
Generating...
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    My_acc.solve()
  File "/root/yyz/code/Emotion-Guided-Piano-Accompaniment-Generation/utils/Accompaniment_Generator.py", line 167, in solve
    self.texture_design(input_fs = "generate_midi/"+ music.split(".")[-2]+"_chd.mid"
  File "/root/yyz/code/Emotion-Guided-Piano-Accompaniment-Generation/utils/Accompaniment_Generator.py", line 158, in texture_design
    midi = render_acc(pianoRoll, chord_table, query_seg, path, shift, acc_pool, 'data/VA-VAE_master.pt')
  File "/root/yyz/code/Emotion-Guided-Piano-Accompaniment-Generation/utils/AccoMontage.py", line 174, in render_acc
    est_x = model.inference(pr_matrix, gt_chord, sample=False)
  File "/root/yyz/code/Emotion-Guided-Piano-Accompaniment-Generation/models/model.py", line 125, in inference
    dec_z = torch.cat([z_chd, z_rhy], dim=-1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 21 but got size 16 for tensor number 1 in the list.

**Comment by Duoluoluos** [comment]
It seems that "jigs116", one of the demo melody files **do not** fit for the phrase limit, since our model is based on phrase-level generation. Try "melody.mid" instead, which tailors the phrase  split demand.
